name: 'Terraform'

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: hashicorp/setup-terraform@v1

      - name: Init
        run: |
          echo "access_key = \"${{ secrets.S3_ACCESS_KEY }}\"" > backend.conf
          echo "secret_key = \"${{ secrets.S3_SECRET_KEY }}\"" >> backend.conf
          terraform init -backend-config=backend.conf

      - name: Validate
        run: terraform validate

      - name: Check format
        if: github.event_name == 'pull_request'
        run: terraform fmt -check

      - name: Plan
        run: terraform plan -input=false -backend-config=backend.conf
        env:
          TF_VAR_PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -backend-config=backend.conf
        env:
          TF_VAR_PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
